# Generated by Django 5.0.3 on 2024-04-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_student_user_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
