# Generated by Django 5.0.3 on 2024-04-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
        ('course', '0005_student_user_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='department_courses', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ManyToManyField(blank=True, related_name='school_courses', to='accounts.school'),
        ),
    ]
