# Generated by Django 5.0.3 on 2024-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
        migrations.AddField(
            model_name='course',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='courses/files'),
        ),
    ]
