# Generated by Django 5.0.3 on 2024-04-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_event_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starting_time']},
        ),
    ]
