# Generated by Django 5.0.3 on 2024-04-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_event_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created']},
        ),
    ]
