# Generated by Django 5.0.3 on 2024-04-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
