# Generated by Django 5.0.3 on 2024-04-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_school_alter_customuser_role_and_more'),
        ('course', '0005_student_user_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(related_name='course_departments', to='course.course'),
        ),
        migrations.AddField(
            model_name='school',
            name='courses',
            field=models.ManyToManyField(related_name='course_schools', to='course.course'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20),
        ),
    ]
